name: iOS-ipa-build
on:
  workflow_dispatch:
jobs:
  build-ios:
    name: 🎉 iOS Build
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          architecture: x64
      - run: flutter pub get
      
      # Complete cleanup of iOS build and pods
      - name: Clean iOS build
        run: |
          cd ios
          rm -rf Pods
          rm -f Podfile.lock
          rm -f .symlinks
          rm -f Podfile
          
      # Create new Podfile
      - name: Create new Podfile
        run: |
          cd ios
          cat > Podfile << EOL
          platform :ios, '15.5'
          
          target 'Runner' do
            use_frameworks!
            use_modular_headers!
            
            flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
            
            target 'RunnerTests' do
              inherit! :search_paths
            end
          end
          
          post_install do |installer|
            installer.pods_project.targets.each do |target|
              flutter_additional_ios_build_settings(target)
              target.build_configurations.each do |config|
                config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.5'
              end
            end
          end
          EOL
          
      # Install pods
      - name: Install Pods
        run: |
          cd ios
          pod install --repo-update
          
      - run: flutter build ios --release --no-codesign
      
      # Create IPA
      - name: Create IPA
        working-directory: build/ios/iphoneos
        run: |
          mkdir Payload
          mv Runner.app Payload/
          zip -r FlutterIpaExport.ipa Payload
          
      # Upload IPA
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build/ios/iphoneos/FlutterIpaExport.ipa
          tag: v1.0
          overwrite: true
          body: "This is first release"
