name: iOS-ipa-build
on:
  workflow_dispatch:
jobs:
  build-ios:
    name: 🎉 iOS Build
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          architecture: x64
      - run: flutter pub get
      
      # Clean iOS build
      - name: Clean iOS
        run: |
          cd ios
          rm -rf Pods
          rm -f Podfile.lock
          
      # Update Podfile correctly
      - name: Update Podfile
        run: |
          cd ios
          # Remove any existing platform declaration
          sed -i '' '/^platform/d' Podfile
          # Add platform declaration at the top
          sed -i '' '1i\
          platform :ios, '\''15.5'\''\
          ' Podfile
          
      # Install pods
      - name: Install Pods
        run: |
          cd ios
          pod install --repo-update
          
      - run: flutter build ios --release --no-codesign
      
      # Create IPA
      - name: Create IPA
        working-directory: build/ios/iphoneos
        run: |
          mkdir Payload
          mv Runner.app Payload/
          zip -r FlutterIpaExport.ipa Payload
          
      # Upload IPA
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build/ios/iphoneos/FlutterIpaExport.ipa
          tag: v1.0
          overwrite: true
          body: "This is first release"
